### ISSUE TITLE
Feature Request: isPlayerTalking

### ISSUE THREAD

**Issue by ali-exacute** [FrazzIe/mumble-voip#10]
Something like `NetworkPlayerTalking` so for example it can be used for drawing talking players on screen or use it on idoverhead and maybe more

**Comment by FrazzIe** [comment]
Just use `NetworkPlayerTalking`? that's what i use as well https://github.com/FrazzIe/mumble-voip/blob/master/client.lua#L131

**Comment by ali-exacute** [comment]
My bad. I thought it doesn't work on mumble
