### ISSUE TITLE
Problem with Installing | Don't know if right here?

### ISSUE THREAD

**Issue by Scania01** [FrazzIe/mumble-voip#2]
Hey there. If this is the wrong place for this, please just tell me. I think i have a Problem with Installing this script. So I can hear everyone from everywhere. I downloaded this script, put it on my server and added "setr voice_use3dAudio true" and "setr voice_useSendingRangeOnly true" to my server.cfg. Are there any other steps or resources or something else I need? I'm running on ESX without Onesync.

**Comment by Scania01** [comment]
Btw. I'm like 120% sure, that there is no other script on my server, which could affect the voicechat.

**Comment by ali-exacute** [comment]
you need to enable onesync or it will not work
mumble is a part of onesync

**Comment by Scania01** [comment]
Okay, thanks for that Information. When I asked in the Forum then nobody wrote, that this is needed.
