### ISSUE TITLE
An idea for spectator voice

### ISSUE THREAD

**Issue by ali-exacute** [FrazzIe/mumble-voip#21]
I am not sure will it work or not,
But the idea is maybe have some export like `setTalkingPed(ped)` and instead of getting own player pedId coords, get the one that we just set.
Sorry for my english , hope this make sense

**Comment by FrazzIe** [comment]
I understand what you mean, and i could have done this with the current version but at the moment with what i'm working on in the dev branch it might be a bit harder to do than before.

**Comment by FrazzIe** [comment]
moved to #4
