### ISSUE TITLE
Mumble VOIP & RP-Radio issues

### ISSUE THREAD

**Issue by PurchasedGaming** [FrazzIe/mumble-voip#26]
Hello Frazzle,

I hope you are doing well, I have recently installed mumble VoIP and RP radio, I will list below my issues:

Mumble VOIP:

Currently, Mumble VOIP is server-wide, regardless of what distance someone is at, they are heard, I am also using setr voice_use3dAudio true & setr voice_useSendingRangeOnly true. This isn't making any changes

RP-Radio:
RP Radio isn't being loaded into my server correctly at all, It isn't loaded even though it says its been started.

**Comment by PurchasedGaming** [comment]
Mumble VOIP Fixed, Just RP Radio that doesn't work now

**Comment by PurchasedGaming** [comment]
Current "Control F" Found relating to RP-Radio
Found new resource rp-radio in /home/zap549555/g258448/gta5-fivem/server-data/resources//rp-radio
Started resource rp-radio

**Comment by question1231** [comment]
Hey, how did you fix the Mumble VOIP issue? I am currently facing it :)

**Comment by FrazzIe** [comment]
Looks like a setup/installation issue, ask for help from other users in the fivem topic.
Here is a pretty detailed tutorial on how to set everything up: https://www.youtube.com/watch?v=-PBXXtpMNAQ

**Comment by PurchasedGaming** [comment]
Hello Frazzle, Everything is setup in that video and i have RP-Radio somewhat working, its working although the hud in the top left when opening radio is not showing

any help would be amazing

Thanks

**Comment by PurchasedGaming** [comment]
![image](https://user-images.githubusercontent.com/51837015/88799596-a286c280-d19e-11ea-8e45-b37e9120c294.png)
