### ISSUE TITLE
Mumble voip + rp radio Without Onesync

### ISSUE THREAD

**Issue by ensaner** [FrazzIe/mumble-voip#31]
Hi, the onesync server works great, but I would need a server without onesync. Is it possible to set it somehow?
The radio on the server without onesync simply cannot be heard.

**Comment by FrazzIe** [comment]
mumble only works with onesync, its built in to fivem but only works with onesync. Onesync is better than non-onesync in every way and there is absolutely no reason not to be using it. it is free with 32 slots like "non-onesync".

**Comment by daviten74** [comment]
Yo solo uso +set onesync on

Pero escucho voces de gente que esta en otra punta del mapa.

**Comment by k3nnyq3** [comment]
Onesync is absolutely in no way better imo. So far, it has only caused fps drops, and connection drops (sure enough i have a very shitty ping, but going with and without onesync, the difference is day and night. Onesync = connection interrupted all the time, nothing is synced, no onesync = even npc is not desynced (ping 400) and everything is working perfectly.

**Comment by ghost** [comment]
> Onesync is absolutely in no way better imo. So far, it has only caused fps drops, and connection drops (sure enough i have a very shitty ping, but going with and without onesync, the difference is day and night. Onesync = connection interrupted all the time, nothing is synced, no onesync = even npc is not desynced (ping 400) and everything is working perfectly.

100% agree with you. Onesync is just terrible for certain things
