### ISSUE TITLE
using the use3daudio option on the dev branch does not work and seems to make voices global

### ISSUE THREAD

**Issue by drnick7000** [FrazzIe/mumble-voip#5]
The 3d audio option in the config does not seem to work and it makes everyone able to hear and speak globally. It works fine without this option however. 

(Yes I have added the requirements to server.cfg)

**Comment by gullidog** [comment]
+1 :)

**Comment by drnick7000** [comment]
Have you made any more progress with this since? Have had a quick look into it myself but haven't made it work yet so was wondering if you had got any further with it. @FrazzIe

**Comment by FrazzIe** [comment]
I've been no-lifing last oasis, haven't looked at anything recently

**Comment by rex2630** [comment]
For me its global even with 3d  voice disabled on dev branch and bunch of errors can be found in the console.

**Comment by mejmej** [comment]
Hey Frazzle :) Love the resource and finally I almost feel that we can ditch teamspeak, but the only thing we need to be able to remove teamspeak is that 3dsound :) Any progress so far? :D

**Comment by TraficOfPeras** [comment]
Yeah with 3d some times we hear everyone, some times we don't ear anyone... But, what I noticed is that when we enter the server we hear all the people talking * ear rape * for about 5 minutes. I tried to use the fix they posted on the forum but apparently for the mumble it didn't work. Thanks for listening. https://forum.cfx.re/t/initial-voice-range-needs-to-be-reduced-and-actually-set/368351

**Comment by mejmej** [comment]
Any updates on this issue? :)
